name: festim2-docs
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx
  - matplotlib
  - sphinx
  - folium
  - numpy
  - tqdm
  - scifem>=0.20.0
  - io4dolfinx
  - h5py =*=mpi_*
  - sphinx-design
  - sphinxcontrib-bibtex
  - sympy
  - sphinx-book-theme
  - sphinx-copybutton
  - pillow
  - pip
  - pip:
      - pyalex
